### ISSUE TITLE
As a user(any role) I want to view Note Page

### ISSUE THREAD

**Issue by VitaliiKulinskyi** [ita-social-projects/dokazovi-be#100]
User (any role) should view material in Note Page

Note Page content should contain:

- Expert section 
- Article section

Expert section:

- Author's picture
- First name, last name
- Place of work

<img width="233" alt="author" src="https://user-images.githubusercontent.com/71768856/101138639-24896b00-3619-11eb-96f0-503ad6e6b844.png">

Click on “First name, last name” should redirect to "Expert Page" 

 
Note section:

- Note title
- Direction
- Material
- Date of adding

Material should contain text that is provided by the author.

<img width="380" alt="notepage" src="https://user-images.githubusercontent.com/71768856/101138735-42ef6680-3619-11eb-90c0-a19adda32d46.png">

Click on direction’s value should redirect to "Direction page" 
 
AC:

- Expert section  is displayed
- Note section is displayed
- Click on “First name, last name” should redirect to "Expert Page"
- Click on direction’s value should redirect to "Direction page"

**Comment by dmytrolyakhovenko** [comment]
BA checked
(Expert section - place of work is not visible)
