### ISSUE TITLE
As a user(any role) I want to view materials in "Important" section

### ISSUE THREAD

**Issue by y-udov** [ita-social-projects/dokazovi-be#11]

**Comment by y-udov** [comment]
User (any role) should view materials in "Important"("Важливе") section. 

Clicking on ">" button should change material card to the next in list. If material is last in list, it should be changed to the 1st one. Clicking on "<" button should change material card to the previous in list. If material is 1st in list, it should be changed to the last one.

Each material card should contain Author's picture, first name, last name, primary place of work, material type (article, note, video, course etc.), direction and title.

Material page should be opened by clicking on material card.

![image](https://user-images.githubusercontent.com/72263170/97916998-7ca02980-1d5c-11eb-9110-8118a4d22f78.png)

AC:
- Important material cards are present in "Important"("Важливе") section
- Each card contains Author's picture, first name, last name, primary place of work, material type (article, note, video, course etc.), direction and title
- click on material card redirects user to the material page
- Button ">" change the cards to the next in list
- Button "<" change the cards to the previous in list

**Comment by SergeOlabin** [comment]
FE:
- [ ] https://github.com/ita-social-projects/dokazovi-fe/issues/10
- [ ] https://github.com/ita-social-projects/dokazovi-fe/issues/17

**Comment by vitaliyhere** [comment]
BA check 19/07/21 
Not accepted.

“Important” section was modified.
