### ISSUE TITLE
As a user(any role) I want to view materials in "Newest" section

### ISSUE THREAD

**Issue by y-udov** [ita-social-projects/dokazovi-be#12]

**Comment by y-udov** [comment]
User (any role) should view materials in "Newest"("Найновіше") section.

Each material card should contain:
- Author's picture, first name, last name, primary place of work 
- Material type (article, note, video, course etc.), direction and title. For articles, notes: preview of material (4 lines). For video: player preview
- Date of adding

Materials should be sorted by date of adding, newest to oldest.

Clicking on "More materials" (Більше матерілів) should load 6 more materials to section and focus the page on them.

Material page should be opened by clicking on material card.

![image](https://user-images.githubusercontent.com/72263170/97920118-a60f8400-1d61-11eb-8999-ca5ce2d1ce52.png)

AC:
- Materials are displayed in materials in "Newest"("Найновіше") section
- Each material card contains: Author's picture, first name, last name, primary place of work, Material type (article, note, video, course etc.), direction and title. For articles, notes: preview of material (4 lines). For video: player preview, Date of adding
- Materials are sorted by date of adding, newest to oldest
- Clicking on "More materials" (Більше матерілів) should load 6 more materials to section and focus the page on them
- Click on material card redirects to Material page

**Comment by SergeOlabin** [comment]
FE:
- [ ] https://github.com/ita-social-projects/dokazovi-fe/issues/18
- [ ] https://github.com/ita-social-projects/dokazovi-fe/issues/11
- [ ] https://github.com/ita-social-projects/dokazovi-fe/issues/20

**Comment by vitaliyhere** [comment]
BA check 18/07/21 
Not accepted.

There is no “Newest” section on the main page.
