### ISSUE TITLE
As a logged-in user (Expert) I want to create Article so that I could post it for reading.

### ISSUE THREAD

**Issue by KarkabsisV** [ita-social-projects/dokazovi-be#122]
**As a** logged-in user(Expert) **I want to** create Article **so that** I could post it for reading. 

Preconditions:
- Registered User is logged in
- Registered User has Active status
- User pressed Create Article button in the header

Articles creation page should contain:
- List of article topics
- Field for entering the title of the article
- List of tags 
- Window with text editor for article 
- Window with text editor for card material text
- Material card 
- Preview button 
- Publish button 

Use #129 User story for list of article topics and tags. 
![изображение](https://user-images.githubusercontent.com/75846007/102496756-7d78ea80-4080-11eb-9059-7a745ca4f0bb.png)

**Text editor for article**
Text Formatting functions:
- Underlined, Bold, Italics text with buttons;
- Normal or Heading text style, changing text style with button, Normal text style is a default text style.

![изображение](https://user-images.githubusercontent.com/75846007/102496196-c7ad9c00-407f-11eb-9f9a-9704f70e7c35.png)

Adding an Image functions:
- pasting image with Ctrl+V combination or with Paste command from Context Menu;
- adding with button, image can be downloaded from file system or with url.

Adding an Image creates special text block with Image link and Image name. 

![изображение](https://user-images.githubusercontent.com/75846007/102499668-1fe69d00-4084-11eb-8722-40171e2d448d.png)

Use #129 User story for Material card, Text editor for material card text, Preview button, Publish button.
![изображение](https://user-images.githubusercontent.com/75846007/102499563-047b9200-4084-11eb-9712-99248159fb21.png)

Acceptance criteria:

- Topics and tags section is displayed
- Number of chosen topics is from 1 to 3
- Number of chosen tags is from 1 to 3  
- At least one topic and one tag are required
- Title field is displayed
- Title text length is from 10 to 100 symbols      _//уточнить_
- Article editor is displayed
- Article text length is from 2000 to 63206 symbols   _//уточнить_
- Click on Preview button  should redirect to "Preview Page". #127 
- Click on Publish button  should redirect to "Post Page". #99 

SI about Tags **//  Edited** 25.02.2021 by [#184](https://github.com/ita-social-projects/dokazovi-be/issues/184)

**Comment by vitaliyhere** [comment]
BA check 18/07/21 
Not accepted

Article creation page doesn’t have list of tags.
Uploading photo doesn’t work properly when you click to upload an image into the Material (from file system).
Adding an Image doesn’t create special text block with Image link and Image name.
Tags are not displayed.
Length for title text length and and text length are not approved.

**Comment by vitaliyhere** [comment]
BA check 20/07/21
Not accepted.

The design and functionality are outdated.  See new design and enhanced functionality for creating Article here(https://github.com/ita-social-projects/dokazovi-be/issues/280).
