### ISSUE TITLE
As a logged-in user (Expert) I want to create Note so that I could post it for reading.

### ISSUE THREAD

**Issue by KarkabsisV** [ita-social-projects/dokazovi-be#123]
**As a** logged-in user(Expert) **I want to** create Note **so that** I could post it for reading. 

Preconditions:
- Registered User is logged in
- Registered User has Active status
- User pressed Create Note button in the header

Notes creation page should contain:
- List of topics
- List of tags 
- Window with a text editor for the Note 
- Window with a text editor for card material text
- Material card 
- Preview button 
- Publish button 

Use #129 User story for list of article topics and tags. 
![изображение](https://user-images.githubusercontent.com/75846007/102590648-87026100-4119-11eb-8f94-2b777bd1db0a.png)

**Text editor for article**
Text Formatting functions:
- Underlined, Bold, Italics text with buttons.

![изображение](https://user-images.githubusercontent.com/75846007/102590865-d052b080-4119-11eb-8152-976c8bc6f676.png)

Adding Image functions:
- pasting image with Ctrl+V combination or with Paste command from Context Menu;
- adding with a button, an image can be downloaded from a file system or with URL.

Adding an Image creates a special text block with an Image link. 

![изображение](https://user-images.githubusercontent.com/75846007/102590937-ec565200-4119-11eb-92e3-9c61d3bd23c2.png)

Use #129 User story for Material card, Text editor for material card text, Preview button, Publish button.
![изображение](https://user-images.githubusercontent.com/75846007/102591155-3a6b5580-411a-11eb-8982-98edef4d6d68.png)

Acceptance criteria:

- Topics and tags section is displayed
- Number of chosen topics is from 1 to 3
- At least one topic is required
- Article editor is displayed
- Article text length is from 2000 to 63206 symbols   _//уточнить_
- Click on the Preview button  should redirect to "Preview Page". #127 
- Click on Publish button  should redirect to "Post Page". #99 

SI about Tags **// Edited** 25.02.2021 by #184

**Comment by vitaliyhere** [comment]
BA check 18/07/21 
Not accepted.

Notes creation page doesn’t have list of tags.
Uploading photo doesn’t work properly when you click to upload an image into the Material (from file system).
Adding an Image doesn’t create special text block with Image link and Image name.
Tags are not displayed.
Length for text length is not approved.

**Comment by vitaliyhere** [comment]
BA check 20/07/21
Not accepted.

The design and functionality are outdated. See new design and enhanced functionality for creating Note here(#280).
