### ISSUE TITLE
As a logged-in user I want to create Video-post so that I could publish it

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#124]
**As a** logged-in user **I want** to create Video-post **so that** I could publish it.

**Preconditions:**
- Registered User is logged in
- Registered User has Active status
- User pressed Create Video button in the header

Video creation page should contain:
- List of topics
- The video title 
- The editor
- Preview button
- Publish button

![image](https://user-images.githubusercontent.com/75846007/110121969-b4c97e80-7dc7-11eb-8f68-459df029e9e4.png)

**Topics section.**
Use #129 User story for the list of the topics.

**The editor**
Editor functions:
- Video addition
- Underlined, Bold, Italics text
- Normal or Heading text style, changing text style with button
- The picture addition us unavailable

**Buttons.**
Use #129 User story for Preview button, Publish button. By default buttons are unlabeled. Buttons become active after downloading the video and adding the description.

**Acceptance criteria:**
- Topics section is displayed
- The video title length is from 10 to 1000 symbols
- Number of chosen topics is from 1 to 3
- At least one topic are required
- The editor is displayed
- Description length is from 2000 to 63206 symbols //уточнить. может ли быть без описания?
- Normal text style is a default text style
- Preview and Publish buttons are unlabeled until downloading the video and filling the description.
- Click on Preview button should redirect to "Preview Page". #125 
- Click on Publish button should redirect to "Post Page". #128

**Comment by vitaliyhere** [comment]
BA check 18/07/21 
Not accepted.

Preview button is active before downloading the video and adding the description.
Description length is not approved.
Note:  there is specific way of downloading video from youtubewhich not suitable for majority of users.

**Comment by vitaliyhere** [comment]
BA check 20/07/21
Not accepted.

Preview button is active before downloading the video and adding the description.
Description length is not approved.
To choose at least one topic is not implemented as an obligatory requirement - you can preview video-post without choosing a single topic.
UI design is outdated.
