### ISSUE TITLE
To view the Video Post Preview

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#125]
**As a  logged-in user (Expert) I want to View Video-post Preview so that I could see if it`s ready to post** 

Each user with the Expert role should be able to see the Post Preview during creating a Video Post.

Preconditions:
- Registered User is logged in.
- User has already loaded a video and filled in the Video Description section.
- User pressed the Preview button at the create Video page #124 
- UI for creating a video post looks like described here #280 

**For Video Post Preview example look here:**

https://drive.google.com/drive/u/0/folders/10RJuqgY57nK-oOo8pre1AYFhkbR5I5hd

Video post preview page should contain:
- Expert section.
- Video section.
- Description section.
- Button Back to editing.

**Expert section**

Expert section includes:
  - Author's picture. 
  - First name, last name.
  - Author’s bio

**Video section**
The section includes:
- Title.
- Topic.
- Video player.
- Video description.

Video section contains a built-in Youtube player.
Video description section contains material`s text. 
 
**Buttons.**
Click on "Back to editing" should redirect to the "Create Video Post" page.  #124 
Page should be prefilled with the user`s content (Topics, Title, Video, Video description).
 

**Acceptance criteria:**

- Expert section is displayed.
- Video is displayed.
- A text description of the video is displayed.
- Click on “First name, last name, Expert Photo” should redirect to "Expert Page".
- Click on topic’s value should redirect to "Topic page".
- Click on "Back to editing" should redirect to "Create Post".

Out of scope(Changed by SI #184 )

Epic [#187](https://github.com/ita-social-projects/dokazovi-requirements/issues/187)

**Comment by vitaliyhere** [comment]
BA check 19/07/21 
Not accepted.

What’s “topic value”?

**Comment by vitaliyhere** [comment]
BA check 21/07/21
Not accepted.

Expert section link doesn't work.
There is no "Topic Page" on the site. There are topics named "Теми" which expert can choose(from 1 to 3) from the list when he creates Material though (#129).
What’s “topic value”?
The UI design is outdated.
User can not publish his video.
