### ISSUE TITLE
To View Article/Note Preview

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#127]
**As a logged-in user (Expert) I want to View Article/Note Preview so that I could see if it`s ready to post**

Each user with the Expert role should be able to see the Post Preview during creating an Article or Note.

**For Article Preview and for Note Preview examples look here:**

https://drive.google.com/drive/u/0/folders/10RJuqgY57nK-oOo8pre1AYFhkbR5I5hd

Post Preview page should contain:
- Expert section.
- Article section.

_Expert section includes:_

 - Author's picture.
 - First name, last name.
 - Author’s bio

_Article or Note section includes:_
- Article title.
- Topic.
- Material.
- Button Back to editing.

Post-Preview material must contain a text. Article Preview material should also contain pictures that are provided by the author. All pictures should be named.

**AC:**

- Expert section is displayed.
- Article section is displayed.
- Click on “First name, last name,  Expert Photo” should redirect to "Expert Page".
- Click on "Topic" should redirect to "Topic Page".
- Click on the topic's value should redirect to "Topic page".
- Click on "Back to editing" should redirect to "Create Post".

Out of scope(Changed by SI #184 )

Epic #[187](https://github.com/ita-social-projects/dokazovi-requirements/issues/187)

**Comment by vitaliyhere** [comment]
BA check 18/07/21 
Not accepted.

Expert section doesn’t include city and place of work.
What’s “topic value” in preview?

**Comment by go-ann** [comment]
> BA check 18/07/21
> Not accepted.
> 
> Expert section doesn’t include city and place of work.
> What’s “topic value” in preview?

this story describes out-dated design. may be BAs need to provide new story taking into account figma.

**Comment by vitaliyhere** [comment]
There is no "Topic Page" on the site. There are topics named "Теми" which expert can choose(from 1 to 3) from the list when he creates Material though (https://github.com/ita-social-projects/dokazovi-be/issues/129.
