### ISSUE TITLE
As a user (any role) I want to View Video-post so that I could get information

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#128]
Each user should be able to see Video-post Page.

Video-post Page should contain:
- Expert section
- Video section

Expert section:
- Author's picture
- First name, last name
- Place of work

Click on “First name, Last name, Expert Photo” should redirect to "Expert Page"

Video section:
- Video title
- Topic
- Build-in Youtube video player
- Video description
- Date of adding

Click on Topic should redirect to Topic Page.

https://ninjamock.com/s/N2ZF1Gx

**Comment by dmytrolyakhovenko** [comment]
BA checked
