### ISSUE TITLE
To choose Title, Text for Material card

### ISSUE THREAD

**Issue by VitaliiKulinskyi** [ita-social-projects/dokazovi-be#129]
**As a logged-in user (Expert) I want to choose Title, Text for Material card on the Article/Note page so that I can create the correct material.** 

UI for Creation Page(Editor) is described in user story #280 

**Each user with the Expert role should be able to choose Title/s for his Article/Note**

List of topics:

<img width="156" alt="topic" src="https://user-images.githubusercontent.com/72273859/129606506-8e204e17-e23f-4f36-806f-d086647b2feb.png">

AC:
Experts should be able:
- select 1-3 topics from the list
- change the choice of topic

Clicking on the topic name adds it to the list of selected topics
Сlicking on a topic deselects the topic

**Each user with the Expert role should be able to create Text for Material card for his Article/Note**

Window with a text editor for material card text:

<img width="431" alt="texteditor" src="https://user-images.githubusercontent.com/71768856/102690098-b5606900-420b-11eb-890c-1c81ba4f589b.png">

AC:

- By default, the text of the card is taken from the beginning of the text of the Article/Note
- Expert should be able to edit the text of the card
- Change text should be displayed on card preview
- Text for Material card length is from 10 symbols and up to 150 symbols.

**Each user with the Expert role should be able to see text for Material card preview**

UI for different types of material cards are described in user story #229 

Epic #[187](https://github.com/ita-social-projects/dokazovi-requirements/issues/187)

**Comment by vitaliyhere** [comment]
BA check 18/07/21 
Not accepted.

The list of available topics on site is smaller than the list of topics represented on design.
Tags are not implemented on the site.
The text of the card is not taken from the beginning of the text of the Article/Note.
Material card does not contain primary place of work.

**Comment by vitaliyhere** [comment]
BA check 20/07/21
Not accepted.

The list of available topics on site is smaller than the list of topics represented on design(outdated design).
Tags are out of scope for first release(https://github.com/ita-social-projects/dokazovi-be/issues/280).
Material card was redesigned(https://github.com/ita-social-projects/dokazovi-be/issues/229).
Text for Material card length is from?
Expert can not pubish content.
