### ISSUE TITLE
As a user(any role) I want to view the pictures of experts in "Experts" section

### ISSUE THREAD

**Issue by y-udov** [ita-social-projects/dokazovi-be#13]

**Comment by y-udov** [comment]
User (any role) should view pictures of experts in "Experts"(Експерти) section.

Expert's photo should be displayed randomly. 

![image](https://user-images.githubusercontent.com/72263170/97923286-6ac38400-1d66-11eb-93d6-5c68c865f660.png)

On hover information about expert should appear near photo. Information should contain:
- First name, last name
- Specializations
- Place of work
- Position
- Last added material title (if exist)

Click on "First name, last name" should redirect to "Expert" page.
Click on "Last added material title" should redirect to "Material" page.

![image](https://user-images.githubusercontent.com/72263170/97923253-5d0dfe80-1d66-11eb-93b4-a7a98833bf2c.png)

AC:
- Expert's photo are displayed
- On hover information about expert appears near photo
- Information about expert contains first name, last name, specializations, place of work, position, last added material title (if exist)
- Click on "First name, last name" redirects to "Expert" page.
- Click on "Last added material title" redirects to "Material" page.

**Comment by SergeOlabin** [comment]
FE: 
- [ ] https://github.com/ita-social-projects/dokazovi-fe/issues/22
- [ ] https://github.com/ita-social-projects/dokazovi-fe/issues/23
- [ ] https://github.com/ita-social-projects/dokazovi-fe/issues/24
- [ ] https://github.com/ita-social-projects/dokazovi-fe/issues/25
- [ ] https://github.com/ita-social-projects/dokazovi-fe/issues/26

**Comment by vitaliyhere** [comment]
BA check 18/07/21 
Not accepted.

There is no “Authors” section on the Main Page.
