### ISSUE TITLE
As a user, I want to have Post Views Count to see how popular material is.

### ISSUE THREAD

**Issue by LiliiaV** [ita-social-projects/dokazovi-be#174]
As a user, I want to see the Views Counter of the material so that I can see how popular the material is.

Preconditions:
1. The user is on the material's full view screen 

Acceptance criteria:

1. The counter displays the total number of unique views of the material.
1.a. If the user opens the material for the second time (and more), the counter's value is not updated.

2. The counter ignores the views of the author of corresponding material (in case an author is logged-in).
3. The value should be updated with each opening of the material (material's full view screen).
4. The users with all roles can see the counter's value.

5. The user with an administrator role should be able to edit the counter's value. - **in the scope of 2nd release** 

TBD (depends on the implementation):

1. If the counter's value is updated straightaway after click - then the user sees the counter value after opening the material
2. If the counter's value is not updated straight away (but after the second opening), - then: when the user opens the material for the first time, the user doesn't see an eye icon and number of views.

UI - an eye icon with the number of views 
[link](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A1168) 

![image](https://user-images.githubusercontent.com/79923250/119377773-2ed21b00-bcc6-11eb-923b-85ab4d64a28c.png)

**Comment by oksanahorishna** [comment]
As a user, I want to have Post Views Count to see how popular material is.

Preconditions:
1. The user is on the material's full view screen 

Acceptance criteria:

1. The counter displays the total number of unique views of the material.
3. The counter ignores the views of the author of corresponding material (in case an author is logged-in).
3. The value should be updated with each opening of the material (material's full view screen).
4. The users with all roles can see the counter's value.
5. The user with an administrator role should be able to edit the counter's value.

Design - an eye icon with the number of views (url)

![image](https://user-images.githubusercontent.com/79923250/119377773-2ed21b00-bcc6-11eb-923b-85ab4d64a28c.png)
