### ISSUE TITLE
As a user, I want to see the time the material was added.

### ISSUE THREAD

**Issue by EleonoraBudanova** [ita-social-projects/dokazovi-be#182]
**Story improvement.** As a user, I want to see the time the material was added.

As-is:
There is only the date of adding materials on the Post page.

To-be:
The Post page shows the date (Ukrainian) and time (military time) of adding materials.
template for date&time: <dd_month,_hh:mm>

Links with a US [#99](https://github.com/ita-social-projects/dokazovi-be/issues/99)

**Comment by VitaliiKulinskyi** [comment]
https://github.com/ita-social-projects/dokazovi-fe/pull/350
