### ISSUE TITLE
SI: As a logged-in user (Expert), I don't want to be able to add tags to a post. 

### ISSUE THREAD

**Issue by EleonoraBudanova** [ita-social-projects/dokazovi-be#184]
**Story improvement.** To hide possibility of adding tags to a post.

As-is:
There is possibility of adding tags to a Article and Note post.

To-be:
To hide possibility of adding tags to a Article and Note post and to search tags in Posts.
There is no requirement for adding at least one tag to publish the material. 

![зображення](https://user-images.githubusercontent.com/75980615/109129912-d25c6f80-7759-11eb-81a3-77d3c8aebd85.png)

Links with a US [#122 ](https://github.com/ita-social-projects/dokazovi-be/issues/122), [#123 ](https://github.com/ita-social-projects/dokazovi-be/issues/123), [#99](https://github.com/ita-social-projects/dokazovi-be/issues/99)

**Comment by EleonoraBudanova** [comment]
There is no mention of tags on the site pages.

**Comment by vitaliyhere** [comment]
BA check 18/07/21 
Accepted.
