### ISSUE TITLE
As an Admin I want to see Delete button on Material page so that I could delete material from site

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#192]
As an Admin I want to see Delete button on Material page so that I could delete material from site

Preconditions:
- Registered User is logged in
- Registered User has Admin role
- Admin opened Material page

Button is displayed on every Material Page (Article, Post, Video etc.)

![image](https://user-images.githubusercontent.com/75846007/109800465-e0acfe80-7c25-11eb-9d51-fe67d12042c4.png)

After pressing button shows the confirmation message about final delete. 
![image](https://user-images.githubusercontent.com/75846007/110472268-d8513980-80e5-11eb-8cd9-cf4181b3b041.png)

If the Admin presses “No” or exit button confirmation message closes. The Material page displays.
If the Admin presses “Yes” Material should be deleted. 
If delete was successful it redirects to the Main page and displays success-notification.
After deleting Material is stored on our data base during the week to be able to restore material from the back-end.
![image](https://user-images.githubusercontent.com/75846007/110471819-477a5e00-80e5-11eb-9230-20301cbf6791.png)

If delete was NOT successful user stays at the Material page and it displays failure-notification.
![image](https://user-images.githubusercontent.com/75846007/110472178-b8ba1100-80e5-11eb-935d-bd7923581af3.png)

AC:
- The User has Admin role
- The Admin should confirm before delete

**Comment by vitaliyhere** [comment]
21/07/21
BA check
Not accepted.

If delete was successful it doesn't redirect to the Main page.
After deleting Material is not stored on our data base during just one week. Material is stored there indefinitely.
If delete was NOT successful system doesn't display "Видалити матеріал *назва матеріалу* не вдалося".
