### ISSUE TITLE
As an Admin I want to see Edit button on Material page so that I could change material

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#193]
As an Admin I want to see Edit button on Material page so that I could change material 
Preconditions:
- Registered User is logged in
- Registered User has Admin role
- Admin opened Material page

Button is displayed on every Material Page (Article, Post, Video etc.)
![image](https://user-images.githubusercontent.com/75846007/109818570-cb42cf00-7c3b-11eb-8e3e-8cff0be1b781.png)

Pressing the button opens the Editing page with prefilled Material content.
Editing page contains all elements of the Creation page and the button «Відмінити редагування». 
Instead of «Опублікувати» the user sees «Зберегти і опублікувати». The button functionality does not change.

![image](https://user-images.githubusercontent.com/75846007/110473267-06834900-80e7-11eb-898c-e4707a618d55.png)

For Article use page from US #122
For Note use page from US #123
For Video use page from US #124

After pressing the button «Зберегти» user should confirm his decision in modal window. Pressing "Так" saves changes and displays Material page. Pressing "Ні" closes modal window, user stays at the edition page. 
![image](https://user-images.githubusercontent.com/75846007/110472627-41d14800-80e6-11eb-8011-3eecd6e2e34a.png)
After pressing the button «Відмінити редагування» user should confirm his decision in modal window. Pressing "Так" cancels edition and displays original Material page. Pressing "Ні" closes modal window, user stays at the edition page. 
![image](https://user-images.githubusercontent.com/75846007/110473659-742f7500-80e7-11eb-8fc6-eb907b307390.png)

Assumption:
The Author and the creating date stay unchanged after saving.

AC:
- The User has Admin role
- Pressed button opens prefilled Editing Page
- The Admin can edit fields «Теми» (Напрямки), «Заголовок», «Текст статті», «Текст картки матеріалу».

**Comment by vitaliyhere** [comment]
Not accepted.

Editing page doesn't have «Зберегти і опублікувати» button.
UI of the editing page is outdated.
A modal window doesn't pop up after pressing the button «Зберегти» , user  is redirected to his Material page immediately.
The design of modal window is outdated.

**Comment by vitaliyhere** [comment]
21/07/21

BA check.
Not accepted.

Editing page doesn't have «Зберегти і опублікувати» button.
A modal window doesn't pop up after pressing the button «Зберегти» , user is redirected to his Material page immediately.
UI of the editing page and of modal window are designed from own mockups so some visual details can be changed/polished or are changing/being polished.
