### ISSUE TITLE
As an unregistered user I want to see the Materials page on the Main menu so that I can see all materials on the Materials page.

### ISSUE THREAD

**Issue by EleonoraBudanova** [ita-social-projects/dokazovi-be#196]
**As** an unregistered user **I want to** see the Materials page on the Main menu **so that** I can see all materials on the Materials page.

**Acceptance Criteria**
1. The Materials page on the Main menu contains the filters section, materials section, and pagination buttons.
2. By clicking on the material cards it is redirecting to the Material Page. 
![image](https://user-images.githubusercontent.com/75980615/111753165-337deb80-889f-11eb-886e-55d6d544e801.png)

The Materials page includes sections:
1. The filters section. 
- More details on how filters work are described **in the US#[236](https://github.com/ita-social-projects/dokazovi-be/issues/236)**
2. The section with all materials cards.
3. The section with pagination pages and a button "Показати ще...".
- More details on how pagination work are described **in the US[#244](https://github.com/ita-social-projects/dokazovi-be/issues/244)**

The filters section includes:
1. The topic filter. 
2. The material type filter:
- "Статті" (article),
- "Дописи" (note),
- "Відео" (video).
3. The material source filter:
- "Думки експертів".
- "Переклади".
- "Медитека". 

The new design of the filters section is available on the Figma [link](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=0%3A1).

The materials section:
- The materials section includes all material cards. 
- The material cards are sorted by date and time of adding. From the newest to the oldest.
- The material cards are arranged on the page in a grid of 3 columns.

The material cards are described **in the US #229**

**Comment by dmytrolyakhovenko** [comment]
BA checked
