### ISSUE TITLE
As a user, I want to see footer to have my pages completed.

### ISSUE THREAD

**Issue by LiliiaV** [ita-social-projects/dokazovi-be#207]
**Description**
Add a footer to the website according to the mockup.
Footer is visible on each page of the website.
Footer includes:
1. Logo "Доказові"
2. Logo "UNICEF"
3. Logo "Softserve"
4. DISCLAIMER - text field, has read-only mode for all roles.
TEXT (assumption): "Використання матеріалів можливе за умови дотримання Правил платформи "Доказові" Статті, блоки та переклади порталу мають просвітнецький характер і не можуть змінити або скасувати консультацій із лікарем(-кою). Ресурс призначено для користувачів від 18 років і старших."
5. Copyright - text ( assumption):
"2021 UNICEF Ukraine. Всі права захищені."
6. "Про платформу" - link, opens a corresponding page.
7. "Правила використання" - link, opens a corresponding page.
8. "Контакти" - link, opens a corresponding page.

![image](https://user-images.githubusercontent.com/75393425/110941972-c9ff5980-8341-11eb-80f5-342bfe15d310.png)

**Comment by VitaliiKulinskyi** [comment]
Дизайн #210 #208 #209

**Comment by Ihor-malyshko** [comment]
all ready done in issue [Footer: redesign #326](https://github.com/ita-social-projects/dokazovi-fe/issues/326)
