### ISSUE TITLE
SI: Redesign the "Important" section on the Main Page. 

### ISSUE THREAD

**Issue by EleonoraBudanova** [ita-social-projects/dokazovi-be#216]
**Story improvement.** 
**As a** user **I want to** see the most important posts at first on the Main Page **so that** I can not miss important information.

**As is:**
"Important" ("Важливе") section contains 3 cards and two buttons - ">" and "<".
![image](https://user-images.githubusercontent.com/75980615/111082613-e5b95a00-8511-11eb-8b00-9c7a0613a8fb.png)

**To be:**
1. The title "Важливе" should be hidden. 
2. There are only 3 post cards.
3. The material card is stretched in width.
4. The user can flip through three material cards by clicking on three dots. 
This is placed at the bottom right of the material card.
5. The three material cards automatically change every 5 seconds.
![image](https://user-images.githubusercontent.com/75980615/111082645-19947f80-8512-11eb-9c1a-e1e087075672.png)

Material cards are described [here](https://docs.google.com/document/d/1EXZ0ewJ6e9T35f-38uwxAUk5dqvO8oPs/edit).
Links with a US #11.

**Comment by EleonoraBudanova** [comment]
Redesign is implemented #296

**Comment by vitaliyhere** [comment]
BA check 19/07/21 
Accepted.
