### ISSUE TITLE
[Change request] To redesign the "Newest" section on the Main Page.

### ISSUE THREAD

**Issue by EleonoraBudanova** [ita-social-projects/dokazovi-be#224]
**As** a user **I want to** see the last published materials cards in the "Newest" section **so that** I can learn the newest information.

**Description:**
1. The title "Найновіше" should be hidden.
2. This section contains 12 materials cards. This is a fixed number. There are 4 columns in this section. There are 3 materials cards in every column.
3. Material cards are described in #229.
4. Material cards are added in the "Newest" section by default after publishing the material. They are sorted by date and time of adding, newest to oldest.
5. "More materials" ("Більше матеріалів") button should be hidden.
 
![image](https://user-images.githubusercontent.com/75980615/111516465-9adf5280-875c-11eb-8d0d-b736a32fad05.png)

The design of the "Newest" section is available on figma mock-up by the [link](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=0%3A1).

**Acceptance Criteria:**
1. Material cards will move when new materials are published. They will move from the left side to the right side and then like a snake.
2. Material page should be opened by clicking on the material card.

**Reason for Change:**
Receiving design from client`s side.

Change request to US #12.

**Comment by EleonoraBudanova** [comment]
The task is closed - https://github.com/ita-social-projects/dokazovi-fe/issues/314

**Comment by vitaliyhere** [comment]
BA check 19/07/21
Not accepted.

“Newest” section was modified.
