### ISSUE TITLE
[Change request] To hide the "Experts" section on the Main Page.

### ISSUE THREAD

**Issue by EleonoraBudanova** [ita-social-projects/dokazovi-be#226]
**As** a user **I do not want to** see the "Experts" section on the Main Page **so that** I will learn the authors information on the special page for this - Authors Page.

**Description:**
Main Page should contain:
- "Important" section,
- "Newest" section

Main Page should NOT contain:
- "Experts" section.

**Reason for Change:**
Receiving design from client`s side.

Change request to US #13

**Comment by EleonoraBudanova** [comment]
It has been already implemented.

**Comment by vitaliyhere** [comment]
BA check 19/07/21 
Not accepted.

There is no “Newest” section on the main page.
