### ISSUE TITLE
[SKIP for R1] As a user (any role) I want to view the tagline on the Main Page so that I will immediately understand the main idea of the site.

### ISSUE THREAD

**Issue by EleonoraBudanova** [ita-social-projects/dokazovi-be#239]
**As** a user (any role) **I want to** view the tagline on the Main Page **so that** I will immediately understand the main idea of the site.

**Assumption:**
1. It will be on one line.
2. The slogan text, the size of the letters, the indentation from the extreme letters to the line, the length of the line have not yet been approved.
3. This height is 100 pixels.
![image](https://user-images.githubusercontent.com/75980615/112450448-16dd2a00-8d5d-11eb-9f06-d3fe5a592331.png)

**Acceptance Criteria:**
1. The tagline is located on the Main Page between the “Important section” and the “Newest section”.
2. The place for the slogan must be fixed. 
3. The slogan is aligned to the center of the page.
4. The empty space to the left and right of the slogan is filled with a line.

The new design of the slogan must match the design on the Figma [link](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=0%3A1).

**Comment by vitaliyhere** [comment]
BA check 19/07/21 
Not accepted.

The tagline has been skipped for R1
