### ISSUE TITLE
As Admin I want to download card image so that it could form the material card with image

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#240]
**As an** Admin **I want to** download card image **so that** it could form the material card with image

Preconditions:
- Registered User is logged in
- Registered User has Admin role
- Admin is creating or editing the Material

If Material has origin "Думка експерта" it could be published without card image (background image).
If Material has origin "Медитека" or "Переклад" it is obligatory to download card image (background image). 

It uses card image for the Material cards #229 and for Important section https://github.com/ita-social-projects/dokazovi-be/issues/216. 

Acceptance Criteria:
- only Admin has rights to download card image;
- material with origin "Медитека" or "Переклад" could not be published without card image;
- _max&min image size and resolution should be specified_

**Comment by KarkabsisV** [comment]
Подивитися тех таски

**Comment by vitaliyhere** [comment]
21/07/21
BA check

Not accepted.

Site's functionality allows admin to publish the material with origin "Медитека" or "Переклад" without card image. He should not have the capacity to publish material with origin "Медитека" or "Переклад" without card image(background image).
Max & min image size and resolution are not specified.
