### ISSUE TITLE
[Change request] Redesign the Author`s Card on Authors Page

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#241]
**As a** User **I want to** see the Author's card on Authors Page **so that** I would see information about the Author

New design of the Author card is available on the Figma [link](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=0%3A1).

The Author`s Card is a reusable requirement, so it is described by the [link](https://docs.google.com/document/d/1Lr1Dw-NF0jQgnp-l4BdYCei3r2vOpWvIqVWA2CkSdRk/edit).  Author's card on Authors Page is described in document as Style 3.

### The Author card includes:

- Author`s picture
- Author`s first name, last name
- Author`s bio 

The card height is variable and depends on the Author`s bio.

### Acceptance Criteria:
- Click on any objects on the card should redirect to the Author profile #94. 

Used in: US #90, #94

**Comment by dmytrolyakhovenko** [comment]
BA checked
