### ISSUE TITLE
As a user I want to see the filters on The Authors page so that I would take advantage of it for sorting needed authors.

### ISSUE THREAD

**Issue by EleonoraBudanova** [ita-social-projects/dokazovi-be#243]
**As a** user **I want to** see the filters on The Authors page **so that** I would take advantage of it for sorting needed authors.

**Acceptance Criteria:**
1. There is a field for filters on the left side of a page.
2.  This field names “Вибрати авторів”. Name will change on “Вибрані автори” when the user chooses any items.
2. There are two types of filters. Authors can be sorted by topic of materials and by regions.
3. The topics filter reflects only those on which there are materials.
4. All regions display in the filter. Inactive items for filtering display in gray, checkboxes cannot be placed on them.
5. The item in the filter for which there are options for choosing authors is highlighted in bold letters. Users can click for choosing.
6. Those filter items for which there is no information display in gray and are not available for selection.
![image](https://user-images.githubusercontent.com/75980615/112279801-fb0a5300-8c8c-11eb-8c7e-e677aa5ad398.png)
7. When the user removes the last checkbox, the result of the last filter is displayed on the screen and the user can select a new checkbox.

Links with US **#236.**
**New design** of the filters is available on the Figma [link](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=0%3A1).

**Comment by go-ann** [comment]
How the filtration works.

1. By default: 

- all checkboxes are marked,
- the section displays all materials. 

2. After every user's action (mark/unmark checkbox) system refreshes filtration results. 

3. If the user unmarks all checkboxes the section opens all materials.

4. If there are no materials founded it opens the message "Вибачте, за вашим запитом матеріалів не знайдено."

5. If the user uses browser instruments “back/forward page” filtration set will be saved at the list for one step (better for all).
