### ISSUE TITLE
As a user I want to load more items on the page so that I will choose necessary items for me.

### ISSUE THREAD

**Issue by EleonoraBudanova** [ita-social-projects/dokazovi-be#244]
**As a** user **I want to** load more items on the page so that I will choose necessary items for me.

**Preconditions:**
There are a limited number of items on the page.

**Acceptance Criteria:**
1. A user can load 12 extra items on the page by clicking on the "Показати ще 12..." button.
1.1. The button name is "Показати ще 12 авторів" on the bottom of the author's page.
1.2. The button name is "Показати ще 12 матеріалів" on the bottom of the materials page.
![image](https://user-images.githubusercontent.com/75980615/112285787-593a3480-8c93-11eb-8d29-35bb53dccfaa.png)
![image](https://user-images.githubusercontent.com/75980615/112285834-66572380-8c93-11eb-8066-db44ed09efea.png)

2. When the user clicks on this button, an additional 12 items are added to the page. The page will contain a starting set of items and 12 additional ones.
3. The user can press the button an unlimited number of times until the additional items run out.
4. If the last set of items is smaller than 12 items, then the number that is on the page is loaded. 
It will have different names:
4.1. For the materials page:
- "Показати ще 1 матеріал", "Показати ще 2, 3, 4 матеріали" "Показати ще 5, 6, 7, 8, 9, 10, 11, 12 матеріалів".
4.2. For the author's page:
- "Показати ще 1 автора", "Показати ще 2, 3, 4 автора" "Показати ще 5, 6, 7, 8, 9, 10, 11, 12 авторів".
5. When the additional cards run out, the "Показати ще 12..." buttons and a line will not be displayed to the user. 
![image](https://user-images.githubusercontent.com/75980615/114768701-eb54ca80-9d71-11eb-90e3-351000f08a0b.png)

This is reused requirement. 
The new design of the filters is available on the Figma [link](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=0%3A1).
Links with US #196, #90

**Comment by VitaliiKulinskyi** [comment]
Стрілочка не на часі, закриваємо

**Comment by VitaliiKulinskyi** [comment]
@petro-khanenko 

make issue 
fix bug
