### ISSUE TITLE
SPIKE #6: Unit Tests Java & Code Coverage

### ISSUE THREAD

**Issue by KarkabsisV** [ita-social-projects/dokazovi-be#25]
AC:

- [x] Code coverage plugin for GitHub
- [x] Research and compare libraries for Unit Test
- [x] Presentation
- [x] WikiPage

**Comment by nickunderhill** [comment]
[Code Quality and Coverage wiki page](https://github.com/ita-social-projects/dokazovi-be/wiki/Code-Quality-and-Coverage)
