### ISSUE TITLE
As an Admin I want to have an opportunity to publish material on behalf of another user so that I will fill the site with varied materials.

### ISSUE THREAD

**Issue by EleonoraBudanova** [ita-social-projects/dokazovi-be#254]
**As an** Admin **I want to** have an opportunity to publish material on behalf of another registered user **so that** I will fill the site with varied materials.

**Preconditions:**

- Registered User is logged in.
- Registered User has Admin role.
- Admin is creating or editing the Post on the Post Page.

**Acceptance Criteria:**
1. An Admin has an opportunity to publish material on behalf of another author. 
2. When the admin chooses to publish Post on behalf of another author, he needs to assign an origin to the material. There are "Думка експерта" and "Переклад" options. 
- To the "Думка експерта" it will open the drop-down list with authors. The admin will see a list of registered authors on the site, in which he can select the desired author before publishing.
- To the "Переклад" it will open the field for filling information about the initial author.
3. This Post will be displayed on the page of the selected author.

**Comment by vitaliyhere** [comment]
21/07/21
BA check.
Not accepted.

UI is modified and includes "Медитека" option in addition to "Думка експерта" and "Переклад" options.
Drop-down list attached to the "Думка експерта" option doesn't work correctly.
There are no requirements described for "Медитека" option.
