### ISSUE TITLE
[Change request] To redesign the "Newest" section on the Main Page.

### ISSUE THREAD

**Issue by EleonoraBudanova** [ita-social-projects/dokazovi-be#255]
**As a** user **I want to** see the last published materials cards in the "Newest" section **so that** I can learn the newest information.

**Acceptance Criteria:**
1. The field is divided into four parts with names: “Думки експертів”, “Переклади”, “Медитека”, “Відео”. They are clickable. 
2. When the user clicks on the name of each part and a line with an arrow, the Materials page will be opened with the materials sorted by this filter.
3. Every part contains four latest loaded material cards. 
![image](https://user-images.githubusercontent.com/75980615/113039830-c9b7e880-91a0-11eb-8dad-e5e70c9c0175.png)
![image](https://user-images.githubusercontent.com/75980615/113039889-da685e80-91a0-11eb-97ff-c05f886d0342.png)
![image](https://user-images.githubusercontent.com/75980615/113039928-e522f380-91a0-11eb-8225-5c5dff2959ec.png)
![image](https://user-images.githubusercontent.com/75980615/113039994-f66c0000-91a0-11eb-825f-a2ae240f13b7.png)

4. Material cards will move from the left side to the right side when new materials are published. It works for all parts of the "Newest" section. 
5. Material page should be opened by clicking on the material card.
6. Material cards are described in #229.

**Reason for Change:**
Receiving changes from the client`s side. It was approved on the 29th of March.
The design of the "Newest" section is available on Figma mock-up by the [link](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=0%3A1).

Change request to US #12, to CR #224.

**Comment by vitaliyhere** [comment]
BA check 19/07/21 
Not accepted.

"Відео", “Думки експертів”, “Переклади” parts don’t contain four latest loaded material cards.
