### ISSUE TITLE
As a user, I want to open an administrative part to manage different settings.

### ISSUE THREAD

**Issue by LiliiaV** [ita-social-projects/dokazovi-be#261]
For Administratir role.
Add [Адміністрування] button to the dropdown list in the header according to the picture.
1. The button is visible for the user with Administrator role.
2. The button is active.
3. The button opens administrative part of resource. (#262)

![image](https://user-images.githubusercontent.com/75393425/114544972-09cca000-9c64-11eb-9743-67be14c8a5b5.png)

**Epic** #260

**Comment by vitaliyhere** [comment]
22/07/21
BA check.

Accepted.
