### ISSUE TITLE
As a user I want to access editor for different material types so that I can use specific features for my content

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#280]
**As a** user **I want to** access editor for different material types **so that** I can use specific features for my content

**Description**
To create material (post) on the application user should fill in Creation Page.
There is a business rule, which demands different formatting available for different material types. Rules of uploading images and videos also depend on material type. 

**Preconditions**

- Registered User is logged in
- Registered User has Active status
- User pressed Create button in the header

### Acceptance Criteria
**1. General features of creation page**
Feature | Role | Article (стаття) | Note (допис) | Video (відео)
-- | -- | -- | -- | --
Material title | every role | + | + | +
Topics (directions) | every role | 1-3 | 1-3 | 1-3
field "Текст картки матеріалу" | every role | + | + | +
Material card preview | every role | + | + | +
Tags | - | - | - | -

**2. Features for the text formatting**
Feature | Draft | Link | Role | Article (стаття) | Note (допис) | Video (відео)
-- | -- | -- | -- | -- | -- | --
Style "Підзаголовок 1" |![image](https://user-images.githubusercontent.com/75846007/119239039-ed6b2f80-bb4e-11eb-8aa9-38a6cd71ff0c.png) |[link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A633)| every role | + | - | -
Style "Підзаголовок 2" | ![image](https://user-images.githubusercontent.com/75846007/119239010-bf85eb00-bb4e-11eb-9e56-cbd362355581.png)|[link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A633) | every role | + | + | +
Style "Для вступу" | ![image](https://user-images.githubusercontent.com/75846007/120615214-b820e480-c460-11eb-87f2-60b8dfcb6e81.png)|[link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A633) | every role | + | + | +
Style "Для приміток" | ![image](https://user-images.githubusercontent.com/75846007/120614976-7a23c080-c460-11eb-92b3-19397497f60f.png)|[link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A633) | every role | + | + | +
Bold | | | every role | + | + | +
Italic |![image](https://user-images.githubusercontent.com/75846007/119239174-150ec780-bb50-11eb-85cb-852be55926bd.png) |[link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A131) | every role | + | + | +
Underlined | | | every role | + | + | +
Numbered list | | | every role | + | + | +
Not-numbered list (bullets) | ![image](https://user-images.githubusercontent.com/75846007/119239061-1ab7dd80-bb4f-11eb-8c75-2cf529fdb712.png)| [link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A633)| every role | + | + | +
Lower index | | | every role | + | + | +
Upper index | ![image](https://user-images.githubusercontent.com/75846007/119239155-fa3c5300-bb4f-11eb-90c8-f543e54732b6.png)| [link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A131)| every role | + | + | +
Quote | ![image](https://user-images.githubusercontent.com/75846007/119239132-c6612d80-bb4f-11eb-9145-2d23ec6633f7.png)|[link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A131)| every role | + | + | +
Link |![image](https://user-images.githubusercontent.com/75846007/119239148-e7c21980-bb4f-11eb-84e3-42b78fb2401d.png) | [link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A131)| every role | + | + | +
Text color | | | - | - | - | -
Text alingment (right\left\centered) | | | - | - | - | -
Іndents | | | - | - | - | -
Strikethrough | | | - | - | - | -

**3. Features for uploading**
Feature | Role | Article (стаття) | Note (допис) | Video (відео)
-- | -- | -- | -- | --
Image into the Material (from file system) | every role | + | + | -
Image into the Material (via link) | every role | + | + | -
Image caption | every role | + | - | -
Card Image (from file system) | admin | + | + | +
Card Image (via link) | admin | + | + | +
Video into the Material (via Youtube link) | every role | - | - | +
Video into the Material (from file system) | - | - | - | -

**4. Validation for uploading an image into the Material: width=855 px** 

**5. Features for actions with images**
Feature | Role | Article (стаття) | Note (допис) | Video (відео)
-- | -- | -- | -- | --
Deleting image caption (to use image without caption) | every role | + | х | х
Placing few images in a row | - | - | - | -
Image alingment (right\left\centered) | - | - | - | -

**6. Out of scope/Features for the next release**
- Design of the Creation Page and Editor
- Symbol limits for text fields (min&max quantity) 
- Uploading video from file system
- Tags may be added
- Text colour may be added

Used in US: #122, #123, #124, #129  

Epic [#187](https://github.com/ita-social-projects/dokazovi-requirements/issues/187)

**Comment by KarkabsisV** [comment]
Тех таски

**Comment by vitaliyhere** [comment]
BA check 18/07/21 
Not accepted.
Uploading photo doesn’t work properly when you click to upload an image into the Material (from file system).

**Comment by vitaliyhere** [comment]
BA check 20/07/21
Not accepted.

Card Image (from file system) and Card Image (via link) for admin are not implemented correctly.
