### ISSUE TITLE
As a registered user I want to log in using email and password so that I can get access to my account and to create a material.

### ISSUE THREAD

**Issue by y-udov** [ita-social-projects/dokazovi-be#29]
Links with Change request #215

**Comment by y-udov** [comment]
Registered user should have possibility to log in using email and password by clicking on "Sign in/Register" button in the header and entering correct email and corresponding password to the fields of form in pop-up.

![image](https://user-images.githubusercontent.com/72263170/98346269-63c69b00-201e-11eb-977d-7a17168aeabe.png)

When user enters password characters should be replaced with asterisks ("*").

![image](https://user-images.githubusercontent.com/72263170/98348219-1bf54300-2021-11eb-9ca1-21feacde3ea3.png)

If user enters wrong email or password, message "Invalid email or password" should appear, email and password fields should be cleared.

![image](https://user-images.githubusercontent.com/72263170/98348282-30d1d680-2021-11eb-920f-ae1094e7bcf6.png)

When user enters the right credentials and clicks on "Sign in" button, or "Enter" button on keyboard, pop-up should disappear and User's photo, first name and second name should be displayed on the right side of the header.

![image](https://user-images.githubusercontent.com/72263170/98347611-4a265300-2020-11eb-8974-f7350b934989.png)

AC:
- Pop-up with sign-in form appears by clicking on "Sign in/Register" button.
- When user enters passwords, characters are replaced with asterisks ("*").
- If user enters the right credentials and clicks on "Sign in" button, or "Enter" button on keyboard, pop-up disappears and User's photo, first name and second name are displayed on the right side of the header.
- If user enters wrong email or password, message "Invalid email or password" appears, email and password fields are cleared.

**Comment by LiliiaV** [comment]
The possibility of registrations on the site should be closed for a while.
Only pre-registered users could sign in.
Show on FE short form for log in according to the mockup.
![image](https://user-images.githubusercontent.com/75393425/102368836-fcf4b400-3fc3-11eb-890b-92d99a3178c0.png)

AC:
1. Login field
text field accepts 40 symbols Latin alphabet, numbers, special symbols, accept uppercase as lowercase
2. Password field 
text field accepts 40 symbols Latin alphabet, numbers, special symbols, uppercase, lowercase
