### ISSUE TITLE
The Top section of the material

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#311]
**As a** user, **I want to** see the top section of the material **so that** I could find out important details about the material.
Links with #314 

### Description
The top section contains info about who, when, where created the Material and what attributes the Material has.
The new design of the profiles is available on the Figma [link](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=2374%3A20). Green label "Status: Approved" is obligatory to start development.
![image](https://user-images.githubusercontent.com/75846007/121328462-04669b80-c91d-11eb-9492-d328c9db6605.png)

### Acceptance Criteria

**1. In the top section users should see:**

- the breadcrumbs (US #X),    **to add US**
- the author's block,
- the material topics, 
- the material type, 
- the material origin, 
- the material title, 
- the published date,
- the counter (US #174).

**The author's block**
2. Block style depends on the Material origin. 

<div dir="ltr" style="margin-left:-44.05pt;" id="docs-internal-guid-f35a776d-7fff-9655-2239-88a68e7f802b" align="left">
Block style | Origin | Block objects | Draft | Navigation
-- | -- | -- | -- | --
Style 1 | ≠ “Переклад” | 1.Author's picture; 2.Author's first name, last name; 3.Author's bio | ![image](https://user-images.githubusercontent.com/75846007/119823528-9de58480-befd-11eb-87e1-a960a5e35194.png) [link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A1730)     **OR** ![image](https://user-images.githubusercontent.com/75846007/119823747-d84f2180-befd-11eb-8aad-bb9e0e7b4bd8.png) [link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A131)| After clicking redirect to: **Author's profile**
Style 2 | = “Переклад” | 1. Author's first name, last name; 2. Author's bio | ![image](https://user-images.githubusercontent.com/75846007/119823945-0af91a00-befe-11eb-898a-790fc412ddc7.png) [link ](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1296%3A954)| After clicking redirect to: **Materials page, filter: Origin="Переклад"**

</div>

3. Author's bio container width is aligned with text width

**The material topics**
4. Given the material obligatory has 1-3 topics,
and they are shown in the top section
When a user clicks on the topic name
Then it redirects him/her on the Materials page (US #196) 
filtered by the clicked topic

**The material type**
5. Given the material obligatory has 1 type,
and it is shown in the top section
When a user clicks on the type name
Then it redirects him/her on the Materials page (US #196) 
filtered by the clicked type 

**The material origin**
6. Given the material obligatory has 1 origin,
and it is shown in the top section
When a user clicks on the origin name
Then it redirects him/her on the Materials page (US #196) 
filtered by the clicked origin

**The published date**
7. It shows the published date in the format <HH:MM, DD MMMM YYYY>. 
_We also have the created date and modified date in the system. We don't show them on the Material Page._

**Comment by dmytrolyakhovenko** [comment]
BA checked
