### ISSUE TITLE
To filter materials in the Author’s profile

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#312]
**As a** user, **I want to** see the filters in The Author’s profile **so that** I choose materials that I need

The new design of the profiles is available on the Figma [link](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=1965%3A11). Green label "Status: Approved" is obligatory to start development.
![image](https://user-images.githubusercontent.com/75846007/120634213-ad237f80-c473-11eb-99b4-8e352938cfb1.png)

### Acceptance Criteria:
**UI.**

1. There is a filters section on the left side of a page.
2. There are two types of filters:

- by type («за типом»);
- by topic («за темою»).

3. The filter by type displays checkboxes with available materials in the system.   
4. The filter by topic displays checkboxes with available materials in the system.   
5. If the Author has NO materials with some type/topic:  
- this option in the filter becomes disabled;
- the name of the option is typed in gray font.
[example in figma](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=2307%3A603)
![image](https://user-images.githubusercontent.com/75846007/120661061-9b9ca080-c490-11eb-92cd-62e5f147c347.png)

**How the filtration works.**

6. By default:
- all checkboxes are marked;
- the Materials section displays all materials of the Author.
7. After every user's action (mark/unmark checkbox) the system refreshes filtration results.
- If there are only one option available in the filter the user cannot to unmark it.

8. If the user unmarks all checkboxes the section opens all materials.
9. If there are no materials founded it opens the message "На жаль, даних, що відповідають вашому запиту, не знайдено."
[example in figma, use without button](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=2288%3A83)
![image](https://user-images.githubusercontent.com/75846007/120663459-b53ee780-c492-11eb-8fcb-40b0919bddfb.png)

10. If the user uses browser instruments “back/forward page” filtration settings will be available (the system has filtration settings into the URL).

Related to: US #313

**Comment by dmytrolyakhovenko** [comment]
BA checked
