### ISSUE TITLE
To redesign the Author's profile

### ISSUE THREAD

**Issue by go-ann** [ita-social-projects/dokazovi-be#313]
Change request to US #94.

**Reason for Change:**
Receiving design from the client's side.
The new design of the profiles is available on the Figma [link](https://www.figma.com/file/oxKazHLUvWYHjEvSjdcMH3/Dokazovi-5?node-id=2307%3A253). Green label "Status: Approved" is obligatory to start development.
![image](https://user-images.githubusercontent.com/75846007/120663940-2e3e3f00-c493-11eb-80fc-650d06a8390d.png)

### Acceptance Criteria
**1. In the Author's profile users should see:**
- Author's picture
- Author's first name, last name
- Author's bio
- The contacts block (optional)
- The filters block (US #312)   
- The block with the active filter options (US #236)
- The Materials section
- The "More Materials" button (optional, use US #244)

**Author's picture**
2. Out of scope for the first release: animation for the picture size

**Author's bio**
3. The Author's bio is a string. It may contain:
-  letters (both Latin and Cyrillic, upper and lower register), 
- numbers, 
- symbols ((space), ! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _` { | } ~).

**The contacts block**
4. Social network link and E-mail are the author's contacts. They both are optional.
5. If the author has available contacts, the system shows the contacts block. By default, the block is collapsed.
6. After clicking "+" it expands and shows clickable links of available contacts.

**The Materials section**
7. Section contains only the Materials of the Author
8. The Materials are sorted by date: new to old
9. Section contains 12 materials: 4 rows, 3 cards in a row
10. Cards design is described in US #229 

**The "More Materials" button**
11. Button is visible if the Materials section contains more than 12 Materials. It works according to US #244

 Related to: US #94, #236, #244

**Comment by dmytrolyakhovenko** [comment]
BA checked
