### ISSUE TITLE
DB schemas

### ISSUE THREAD

**Issue by melnikovae87** [ita-social-projects/dokazovi-be#7]
Create DB init schemas

**Comment by nickunderhill** [comment]
## DB Diagram:
https://dbdiagram.io/d/5f9974d43a78976d7b798913

## Queries:
https://docs.google.com/document/d/16TsIZWLph-YO4_q6uePvxUoE5zDMsKXiz5N1mWSukG4/edit

## Description:
### **Основні таблиці:**

**users** - користувачі системи (лікарі, адміністратори)
**roles** - ролі користувачів(superadmin, admin, doctor, trusted_doctor)
**directions** - напрямки медицини (Кардіологія, вірусологія, тощо)
**sources** - додаткові матеріли статей, або користувачів(зображення, відео)
**institutions** - медичні заклади
**regions** - області в яких знаходяться заклади
**posts** - публікації
**post_types** - типи публікації - статті, дописи, відео
**tags** - теги публікацій

### **Проміжні таблиці:**

**roles_users** - зберігає ролі, наявні у користувача
**users_institutions** - зберігає заклади, у яких працює користувач
**user_directions** - зберігає напрями, за якими працює користувач
**user_sources** - зберіає медіа користувача, наразі тільки аватар
**post_sources** - зберіає медіа публікацій (зображення, відео, тощо)
**post_tags** - зберіає теги публікацій
**user_directions** - зберігає напрями публікації

**Comment by nickunderhill** [comment]
Wiki page: https://github.com/ita-social-projects/dokazovi-be/wiki/Database
