### ISSUE TITLE
As a user (any role) I want to view Experts list on "Experts" page so that I can choose which one I want to read.

### ISSUE THREAD

**Issue by VitaliiKulinskyi** [ita-social-projects/dokazovi-be#90]
Reused: https://docs.google.com/document/d/1bFocIi4w03yRbd6MOpMxJmFCerebAyfiM4jfDqxY6PM/edit?usp=sharing
As a user (any role) I want to view Experts list on "Experts" page so that I can choose which one I want to read. 

User (any role) should view a list with Experts cards on the Experts page.

Experts page content should contain:
- “Topics” (“Теми”) section; 
- “Region” (“Регіон”) section; 
- Experts list section;
- Expert cards.

Experts list:
- Two columns;
- Three cards in a column; 
- Go to the next list of six cards. 

<img width="256" alt="explist" src="https://user-images.githubusercontent.com/71768856/100627826-29f06800-3330-11eb-994a-ae4cceffda92.png">

Clicking on "1" button should change to the first card list.
Clicking on "2", “3”, etc. button should change to the next card list by number.
Clicking on ">>" button should change the list with cards to the last list.
Clicking on "<<" button should change the list with cards to the first list.

Each Experts card should contain:
- Author's picture;
- First name, last name;
- Topics;
- Place of work;
- Position;
- Last added material title (if it exists).

<img width="231" alt="expcard" src="https://user-images.githubusercontent.com/71768856/100628075-7d62b600-3330-11eb-9335-175c89a4f47e.png">

Click on "First name, last name, place of work”  should redirect to "Expert" page.
Click on "Last added material title" should redirect to "Material" page.

“Topics” (“Теми”) section should contain:
- List of tagged destinations.
- Possibility of filtering by tags with checkbox. 
- By default all topics are chosen.

Click on ` \/ ` button should the full Topic's section come out.
Click on ` /\ ` button should the full Topic's section come back.
Chosen Topics are displayed in the top of section. Chosen regions are displayed after Click on ` /\ ` button.

<img width="461" alt="Topics1" src="https://user-images.githubusercontent.com/71768856/100629339-d41cbf80-3331-11eb-8d49-610e7b61934e.png">
<img width="504" alt="direction2" src="https://user-images.githubusercontent.com/71768856/100629374-e4349f00-3331-11eb-9330-2200fe7b2f6b.png">

“Region” (“Регіон”) section should contain:
- List of regions;
- Possibility of filtering with checkbox;
- By default all regions are chosen. 

Click on ` \/ ` button should the full region's section come out.
Click on ` /\ ` button should the full region's section come back.
Chosen regions are displayed in the top of section. Chosen regions are displayed after Click on ` /\ ` button.

<img width="448" alt="region1" src="https://user-images.githubusercontent.com/71768856/100630325-1692cc00-3333-11eb-95e2-96cf39b9ddb6.png">
<img width="502" alt="region2" src="https://user-images.githubusercontent.com/71768856/100630369-24e0e800-3333-11eb-866f-41eb62a54cae.png">

Results should be sorted by the value of Expert Rating, max to min. If few Experts have equal rating they should be sorted in alphabetic order.
Expert Rating by default is set to the number of posts in PUBLISHED state.
We should have a separate Expert Rating field in the database so that admin could correct it where required.

Sorting rules for search results:
- If a user chooses one or no filtration parameter, results should be sorted by the value of Expert rating (max to min).
- If a user chooses two or more filtration parameters, firstly should be displayed results satisfying maximal number of parameters sorted by value of Expert rating (max to min). Secondly should be displayed results satisfying (max-1) number of parameters sorted by value of Expert rating (max to min). Lastly should be displayed results satisfying 1 parameter sorted by value of Expert rating (max to min).

AC:

- Expert's list is displayed
- Experts list has 6 cards in 2 columns
- Experts list is sorted by Expert rating. 
- Expert's cards are displayed
- Region section is displayed
- Topics section is displayed
- Clicking on "1" button should change to the first card list.
- Clicking on "2", “3”, etc. button should change to the next card list by number.
- Clicking on ">>" button should change the list with cards to the last list.
- Clicking on "<<" button should change the list with cards to the first list.
- Click on "First name, last name, place of work”  should redirect to "Expert" page.
- Click on "Last added material title" should redirect to "Material" page.
- Click on ` \/ ` button should the full Topic's section come out.
- Click on ` /\ ` button should the full Topic's section come back.
- Click on ` \/ ` button should the full region's section come out.
- Click on ` /\ ` button should the full region's section come back.

SI about page name // Edited 25.02.2021 by #183

**Comment by dmytrolyakhovenko** [comment]
BA checked
