### ISSUE TITLE
As a user (any role) I want to view Expert profile on “Expert” page so that I can learn more about certain expert.

### ISSUE THREAD

**Issue by VitaliiKulinskyi** [ita-social-projects/dokazovi-be#94]
User (any role) I want to view information about Expert on “Expert” page.
User (any role) I want to view Expert’s material on “Expert” page.

Experts page content should contain: 
- Profile section.
- Material section. 

Expert’s profile:
- Author's picture;
- First name, last name;
- Position;
- Topics;
- Place of work;
- Phone number;
- Email;
- Info about expert. 

<img width="419" alt="expert" src="https://user-images.githubusercontent.com/71768856/100727953-97070a80-33cf-11eb-84e6-9a6b5032e935.png">

Click on topic’s value should redirect to "Topic page" (Direction page). 

Material section:
- The checkboxes with material types;
- Three columns;
- Three cards in a row;
- "More materials" (Більше матеріалів) button. Button is shown if user has 10 or more materials. 
- If user has no materials it should be written "У користувача поки що немає матеріалів".

Expert’s material card should contain:
- Author's picture, first name, last name, primary place of work.
- Material type (article, note, video, course etc.), topic (direction) and title. For articles, notes: preview of material (3 lines). For video: player preview.
- Date of adding.
- Materials should be sorted by date and time of adding, newest to oldest.

<img width="311" alt="expmaterial" src="https://user-images.githubusercontent.com/71768856/100728244-fbc26500-33cf-11eb-88ce-488079cacf68.png">

Clicking on "More materials" (Більше матеріалів) should load 6 more materials to section and focus the page on them. After loading last available 1-6 materials button "More materials" should be hidden. And the information "No more new materials" ("Більше нових матеріалів немає") appears.
User should have possibility to filter materials by material type.
Material page should be opened by clicking on material card.

Materials section filtration.

By default section displays all materials with Topic (direction) mentioned. All checkboxes are unmarked by default.
If user chooses material type (article/post etc) materials should be filtered as chosen, the section reloads according to user's request.
In case of a user unmarks all checkboxes the section opens all materials.
in case of according to user's request nothing materials are found open the message with text "Вибачте, за вашим запитом матеріалів не знайдено."
If user clicks on some Topic (direction) in material card we redirect him to Topic (direction) page. Page should be in default state (with no filtration).
if user uses browser instruments “back/forward page” filtration set will be saved at list for one step (better for all).

**Comment by dmytrolyakhovenko** [comment]
BA checked
