### ISSUE TITLE
As a user (any role) I want to view Material Full view page so that I can get acquainted with the content

### ISSUE THREAD

**Issue by VitaliiKulinskyi** [ita-social-projects/dokazovi-be#99]
### Changed by change request #311 _(27/05/21)_
 

User (any role) should view material in Post Page.

**Article Page should contain:**
- Expert section. 
- Article section.

**Expert section includes:**
- Author's picture.
- First name, last name.
- City and place of work.

<img width="233" alt="author" src="https://user-images.githubusercontent.com/71768856/101138159-80072900-3618-11eb-8565-da1ab7a99b63.png">

Click on “First name, last name” should redirect to "Expert Page". 

**Article section includes:**
- Article title.
- Tags.
- Topic.
- Material.
- Date of adding.

Click on "Topic" should redirect to "Topic Page".

_For Article page:_
Material must contain text and should contain pictures that are provided by the author.
Picture should be named.

![image](https://user-images.githubusercontent.com/75980615/102507274-b919b180-408c-11eb-95aa-eefea8e6f116.png)

_For Note page:_
Material must contain text and should be limited by number of characters.

![image](https://user-images.githubusercontent.com/75980615/102507760-4826c980-408d-11eb-8b65-2cdc19661930.png)

**AC:**

- Expert section is displayed.
- Article section is displayed.
- Click on “First name, last name” should redirect to "Expert Page".
- Click on Topic’s value should redirect to "Topic page".

SI:
- about Tags **// Edited** 25.02.2021 by #184
- about time of addinf materials **// Edited** 25.02.2021 by #182

**Comment by dmytrolyakhovenko** [comment]
BA checked
